# Docker Compose para MVP Proxy Scraper - AWS PRODUCTION
# Uso: docker compose -f docker-compose.aws.yml up -d

networks:
  proxy-scraper-network:
    driver: bridge

services:
  # ===== BACKEND SERVICE - AWS =====
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: proxy-scraper-backend-aws
    restart: unless-stopped
    ports:
      - "3081:3001"
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=http://frontend
      - CORS_ORIGIN=http://85.219.42.65:3080
      - PORT=3001
    networks:
      - proxy-scraper-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - backend_logs:/app/logs

  # ===== FRONTEND SERVICE - AWS =====
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: production
      args:
        - VITE_API_URL=http://85.219.42.65:3081
    container_name: proxy-scraper-frontend-aws
    restart: unless-stopped
    ports:
      - "3080:80"
    environment:
      - VITE_API_URL=http://85.219.42.65:3081
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    networks:
      - proxy-scraper-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    depends_on:
      backend:
        condition: service_healthy

volumes:
  backend_logs:
    driver: local 