# Docker Compose para MVP Proxy Scraper
# Optimizado para producción con networking y health checks

networks:
  proxy-scraper-network:
    driver: bridge

services:
  # ===== BACKEND SERVICE =====
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: proxy-scraper-backend
    restart: unless-stopped
    ports:
      - "3801:3001"
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=http://frontend
      - CORS_ORIGIN=http://localhost:3800
      - PORT=3001
    networks:
      - proxy-scraper-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      # Solo para logs persistentes
      - backend_logs:/app/logs
  # ===== FRONTEND SERVICE =====
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: production
    container_name: proxy-scraper-frontend
    restart: unless-stopped
    ports:
      - "3800:80"
    environment:
      - VITE_API_URL=http://localhost:3801
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    networks:
      - proxy-scraper-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    depends_on:
      backend:
        condition: service_healthy

  # ===== PRODUCTION ONLY =====
  # Uso: docker compose up -d

volumes:
  backend_logs:
    driver: local 