# Docker Compose para MVP Proxy Scraper - CONFIGURACIÓN HTTP SIMPLE
# Acceso directo: http://servidor:3080 (frontend) y http://servidor:3081 (backend)

networks:
  proxy-scraper-network:
    driver: bridge

services:
  # ===== BACKEND SERVICE =====
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: proxy-scraper-backend
    restart: unless-stopped
    ports:
      - "3081:3001"  # Backend accesible en puerto 3081
    environment:
      - NODE_ENV=production
      - CORS_ORIGIN=http://ec2-3-254-74-19.eu-west-1.compute.amazonaws.com:3080
      - PORT=3001
    networks:
      - proxy-scraper-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - backend_logs:/app/logs

  # ===== FRONTEND SERVICE =====
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: production
    container_name: proxy-scraper-frontend
    restart: unless-stopped
    ports:
      - "3080:80"  # Frontend accesible en puerto 3080
    environment:
      - VITE_API_URL=http://ec2-3-254-74-19.eu-west-1.compute.amazonaws.com:3081
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    networks:
      - proxy-scraper-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    depends_on:
      backend:
        condition: service_healthy

volumes:
  backend_logs:
    driver: local 