# Docker Compose para MVP Proxy Scraper - DESARROLLO LOCAL
# Uso: docker compose -f docker-compose.local.yml up -d

networks:
  proxy-scraper-network:
    driver: bridge

services:
  # ===== BACKEND SERVICE - LOCAL =====
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: proxy-scraper-backend-local
    restart: unless-stopped
    ports:
      - "3801:3001"  # Puerto local diferente para evitar conflictos
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=http://frontend
      - CORS_ORIGIN=http://localhost:3800
      - PORT=3001
    networks:
      - proxy-scraper-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - backend_logs:/app/logs

  # ===== FRONTEND SERVICE - LOCAL =====
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: production
      args:
        - VITE_API_URL=http://localhost:3801
    container_name: proxy-scraper-frontend-local
    restart: unless-stopped
    ports:
      - "3800:80"  # Puerto local diferente
    environment:
      - VITE_API_URL=http://localhost:3801
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    networks:
      - proxy-scraper-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    depends_on:
      backend:
        condition: service_healthy

volumes:
  backend_logs:
    driver: local 